#!/bin/bash
# ⚠️ NOT INSTALLED BY install-service.sh, ON PURPOSE.
#
# Wrapping the gateway in this profile confines reads and breaks bash: macOS
# refuses nested sandbox-exec, so the harness's sandbox probe finds no usable
# backend and refuses to run commands unconfined. Measured, then reverted; see
# SPEC.md. Read confinement needs a sandbox *provider* plugin, or one OS user per
# instance. This script is kept as reference for that work.
# Generate a macOS Seatbelt profile that denies READS of other instances' data.
#
# Why this exists: the harness sandbox fences writes only. Measured, an agent
# could read another agent's directory and a retired bot's token file. Read
# isolation has to come from the OS, applied to the whole gateway so every child
# process inherits it.
#
#   ./write-read-profile.sh <output.sb> <own-home>
#
# Linux has no equivalent here; on Linux this would be a bwrap/landlock profile
# applied the same way, and that is not implemented.
set -uo pipefail
OUT="${1:?usage: write-read-profile.sh <output.sb> <own-home>}"
OWN_HOME="${2:?}"
HOME_DIR="$(dirname "$OWN_HOME")"

{
  echo "(version 1)"
  echo ";; Generated by deepbot. Allow by default, then deny reads of everything"
  echo ";; that belongs to a different instance or a retired bot."
  echo "(allow default)"
  # Retired bots' data: tokens, sessions, configs.
  [ -d "$HOME_DIR/.hermes" ] && echo "(deny file-read* (subpath \"$HOME_DIR/.hermes\"))"
  # Every sibling agent home except our own.
  for candidate in "$HOME_DIR"/dsh-agent*; do
    [ -e "$candidate" ] || continue
    [ "$candidate" = "$OWN_HOME" ] && continue
    echo "(deny file-read* (subpath \"$candidate\"))"
  done
} > "$OUT"
chmod 644 "$OUT"
echo "✅ read profile: $OUT ($(grep -c 'deny file-read' "$OUT") denial(s), own home excluded)"
